services:
  db:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeStudy
      - MYSQL_ROOT_PASSWORD=test123
    restart: always
    ports:
      - 3306:3306

  app:
    depends_on:
      - db
    image: node:18.15.0
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 3000

volumes:
  db_data:
