services:
  db:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeStudy
      - MYSQL_ROOT_PASSWORD=test123
    restart: always
    ports:
    - 3306:3306

volumes:
  db_data:
  
networks:
  network1:
    name: net-01
    external: true
